<?xml version="1.0" encoding="UTF-8"?>
<ekzUseCase xmlns="http://www.brz.gv.at/datenverbund-unis">
	<ekzAnforderung>
		<ekz>string</ekz>
		<ekzBasis>
			<adresse>
				<ort>Wien</ort>
				<plz>1030</plz>
				<staat>A</staat>
				<strasse>Hintere Zollamtstraße 4</strasse>
			</adresse>
			<gebDatum>2001-03-18</gebDatum>
			<geschlecht>W</geschlecht>
			<nachname>string</nachname>
			<orgKey>UNIA</orgKey>
			<requestTimestamp>2018-04-19T15:06:31.162+02:00</requestTimestamp>
			<svnr>string</svnr>
			<vorname>string</vorname>
		</ekzBasis>
		<forcierungskey>string</forcierungskey>
		<kandidaten>
			<kandidat>
				<ekz>string</ekz>
				<ekzBasisdaten>
					<adresse>
						<ort>Wien</ort>
						<plz>1030</plz>
						<staat>A</staat>
						<strasse>Hintere Zollamtstraße 4</strasse>
					</adresse>
					<gebDatum>2001-03-18</gebDatum>
					<geschlecht>W</geschlecht>
					<nachname>string</nachname>
					<orgKey>UNIA</orgKey>
					<requestTimestamp>2018-04-19T15:06:31.162+02:00</requestTimestamp>
					<svnr>string</svnr>
					<vorname>string</vorname>
				</ekzBasisdaten>
			</kandidat>
		</kandidaten>
		<returncode>string</returncode>
		<returntext>
			<text>string</text>
		</returntext>
	</ekzAnforderung>
	<ekzForcierung>
		<ekz>string</ekz>
		<ekzBasis>
			<adresse>
				<ort>Wien</ort>
				<plz>1030</plz>
				<staat>A</staat>
				<strasse>Hintere Zollamtstraße 4</strasse>
			</adresse>
			<gebDatum>2001-03-18</gebDatum>
			<geschlecht>W</geschlecht>
			<nachname>string</nachname>
			<orgKey>UNIA</orgKey>
			<requestTimestamp>2018-04-19T15:06:31.162+02:00</requestTimestamp>
			<svnr>string</svnr>
			<vorname>string</vorname>
		</ekzBasis>
		<forcierungskey>string</forcierungskey>
		<returncode>string</returncode>
		<returntext>
			<text>string</text>
		</returntext>
	</ekzForcierung>
</ekzUseCase>
